export const TIMELINE_DATA = {
  // you only need to duplicate the object bellow and
  // change the year and content to create a new page
  2024: {
    year: "2024",
    previousYear: "2023",
    company: "ADsologist",
    location: "Marketing Agency Toronto, Canada",
    duration: "2023.03 - 2024.09",
    role: "UIUX · Graphic Designer",
    description:
      "Initially hired as a Web & Graphic Designer, I quickly took on greater responsibilities and was promoted to Art Director, leading the creative direction of key projects across branding, app development, and experiential design. I collaborated with a multidisciplinary and CGI designers, as well as game developers, to deliver innovative, cross-platform solutions.",
    skills: [
      "Branding Design",
      "App & Game Development",
      "UI/UX Design",
      "Graphic Design",
      "Product Managing",
    ],
  },
  2023: {
    year: "2023",
    previousYear: "2022",
    company: "ADsologist",
    location: "Marketing Agency Toronto, Canada",
    duration: "2023.03 - 2024.09",
    role: "UIUX · Graphic Designer",
    description:
      "Initially hired as a Web & Graphic Designer, I quickly took on greater responsibilities and was promoted to Art Director, leading the creative direction of key projects across branding, app development, and experiential design. I collaborated with a multidisciplinary and CGI designers, as well as game developers, to deliver innovative, cross-platform solutions.",
    skills: [
      "Branding Design",
      "App & Game Development",
      "UI/UX Design",
      "Graphic Design",
      "Product Managing",
    ],
  },
  "2022-a": {
    year: "2022",
    previousYear: "2021",
    company: "TechTrans Software",
    location: "Dispatch IT Tech Toronto, Canada ",
    duration: "2022.12 - 2023.02",
    role: "UIUX · Graphic Designer",
    description:
      "Led all design efforts at a Toronto-based software company, owning UX/UI for logistics and dispatch tools. Built scalable UI systems and dashboards to support real-time delivery tracking, task management, and logistics data visibility across user roles.",
    skills: [
      "UIUX Design",
      "App & Web Design",
      "Dashboard Design",
      "Graphic Design",
      "Branding",
    ],
  },
  "2022-b": {
    year: "2022",
    previousYear: "2021",
    company: "",
    location: "",
    duration: "",
    role: "",
    description: "",
    skills: [],
  },
  2021: {
    year: "2021",
    previousYear: "2018",
    company: "Freelance",
    location: "Multiple agencies Korea - Canada",
    duration: "2018 - present",
    role: "Visual System Designer",
    description:
      "Over the past 6 years, I’ve led over 300 freelance design projects across branding, packaging, web, and digital experiences — ranging from startups to nationally scaled brands. It shaped a visual spectrum that moves fluidly across formats, from strategy to storytelling.",
    skills: [
      "Branding Design",
      "Web Design",
      "UIUX Design",
      "Graphic Design",
      "Product Managing",
      "Design Strategy",
      "Editorial Design",
      "Prototyping",
      "User Research",
      "Package Design",
    ],
  },
  2020: {
    year: "2020",
    previousYear: "2025",
    company: "MyPotent",
    location: "Wellness brand Seoul, Korea",
    duration: "2020.04 - present",
    role: "Creative Director",
    description:
      "MyPotent was more than a client — it was a long-term brand-building collaboration, where I led every design decision from concept to conversion. From logo and packaging to web, e-commerce UI, and print collateral, I shaped a visual system that could scale across all touchpoints.",
    skills: [
      "Branding Design",
      "Web Design",
      "Visual Guidance",
      "Graphic Design",
      "Product Managing",
      "E-commerce UI/UX",
      "Digital Campaign Asset",
      "Art Director",
      "Package Design",
      "Brand Partnership",
    ],
  },
  2019: {
    year: "2019",
    previousYear: "2025",
    company: "Landed Canada",
    location: "Started college in London Ontario, Fanshawe",
    duration: "2019.08-29",
    role: "Graphic Design",
    description: "",
    skills: [],
  },
  2017: {
    year: "2017",
    previousYear: "2019",
    company: "Brick Italian Bistro",
    location: "Kunsan, Korea",
    duration: "2017.05 - 2019.05",
    role: "General Manager in FOH",
    description:
      "General Manager — oversaw full restaurant operations, team leadership, and service consistency across all shifts. Balanced frontline management with strategic planning, resource coordination, and customer experience ownership.",
    skills: [],
  },
  2014: {
    year: "2014",
    previousYear: "2011",
    company: "Sookmyung Women’s University",
    location: "Seoul, Korea",
    duration: "2016.07 - 2017.05",
    role: "Bachelor of Craft Design ",
    description:
      "My design roots lie in craft.\nAt Sookmyung Women’s University, I studied Craft Design through a rare curriculum that blended modern design thinking with traditional Korean techniques. \n\nSpecializing in textile and ceramic arts, I developed an early sensitivity to form, material, and process — learning not just how to make, but how to interpret. \n\nI also minored in Fashion Design, where coursework in visual merchandising and spatial styling added another layer of visual logic that now informs my branding and storytelling work.",
    skills: [],
  },

  2011: {
    year: "2011",
    previousYear: "2017",
    company: "FOH Manager",
    location: "Seoul, Korea",
    duration: "2011 - 2014",
    role: "Restaurant FOH manager",
    description:
      "FOH Manager — led day-to-day service, staff coordination, and guest experience.Operated as a frontline problem-solver, managing real-time floor dynamics while ensuring consistent delivery of the brand's tone and service quality. Built early habits in teamwork, resource judgment, and calm decision-making under pressure.",
    skills: [],
  },
  2005: {
    year: "2005",
    previousYear: "2008",
    company: "Brent International School",
    location: "Manila Philippine",
    duration: "2005 - 2008",
    role: "International Experience",
    description:
      "Attended an English-based international high school in Manila, gaining early exposure to multicultural communication and global environments.",
    skills: [],
  },
};
